name: buildx-7.4

on:
  schedule:
    - cron:  '30 2 * * 6'
  push:
    branches: master

jobs:
  buildx7414:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -  
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file
        run: |
          cat <<'EOF' > docker-bake.hcl
          group "default" {
              targets = [
                  "7.4-12",
                  "7.4-14",
                  "7.4-16",
              ]
          }

          target "default" {
              context="."
              dockerfile="Dockerfile"
              platforms = [
                  "linux/amd64",
                  "linux/arm64",
                  "linux/arm/v7",
              ]
          }
          
          target "7.4-12" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:7.4-12",
              ]
              args = {
                  PHP_VERSION="7.4",
                  NODE_VERSION="12",
              }
          }
          
          target "7.4-14" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:7.4-14",
              ]
              args = {
                  PHP_VERSION="7.4",
                  NODE_VERSION="14",
              }
          }
          
          target "7.4-16" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:7.4-16",
              ]
              args = {
                  PHP_VERSION="7.4",
                  NODE_VERSION="16",
              }
          }
          EOF
      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          files: docker-bake.hcl
