name: buildx-8.1

on:
  schedule:
    - cron:  '30 2 * * 6'
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -  
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file
        run: |
          cat <<'EOF' > docker-bake.hcl
          group "default" {
              targets = [
                  "8.1-12",
                  "8.1-14",
                  "8.1-16",
              ]
          }

          target "default" {
              context="."
              dockerfile="Dockerfile"
              platforms = [
                  "linux/amd64",
                  "linux/arm64",
                  "linux/arm/v7",
              ]
          }
          
          target "8.1-12" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:8.1-12",
              ]
              args = {
                  PHP_VERSION="8.1",
                  NODE_VERSION="12"
              }
          }
          
          target "8.1-14" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:8.1-14",
              ]
              args = {
                  PHP_VERSION="8.1",
                  NODE_VERSION="14"
              }
          }
          
          target "8.1-16" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:latest",
                  "16nsk/devcontainers:8.1-16",
              ]
              args = {
                  PHP_VERSION="8.1",
                  NODE_VERSION="16"
              }
          }
          EOF
      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          files: docker-bake.hcl
